name: Publish extension
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm install -g tfx-cli
    - run: npm run build --if-present
    - run: tfx extension publish --manifests vss-extension.json --token "${{ secrets.AZURE_DEVOPS_TOKEN }}"
